language: go
go:
  - 1.13.x

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.23.1

script:
  - golangci-lint run
  - env GO111MODULE=on go test -v -race -coverprofile=coverage.txt *.go
after_success:
  - bash <(curl -s https://codecov.io/bash)
