language: go
go:
  - 1.13.x

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test -v -race -coverprofile=coverage.txt backend/*.go
after_success:
  - bash <(curl -s https://codecov.io/bash)
